spring:
  mvc:
    cors:
      mappings:
        /swagger-ui/**:
          allowed-origins: "*"
          allowed-methods: "*"
  servlet:
     multipart:
       max-file-size: 10MB
       max-request-size: 10MB


  application:
    name: rest-api
  datasource:
    url: jdbc:mysql://localhost:3306/organisationworkspace
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    database: mysql
  flyway:
    baseline-on-migrate: true
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/sandbox

      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:18080/realms/sandbox
            user-name-attribute: preferred_username

        registration:
          greetings-app-authorization-code:
            provider: keycloak
            client-id: admin-cli
            client-secret: d4nhjUEW6rS8c9WbxqfSHKnaiEaiYDoX
            scope:
              - openid
              - microprofile-jwt
server:
  port: 8081
springdoc:
  swagger-ui:
    enabled: true
