spring:
  application:
    name: workspace-lib
  datasource:
    url: jdbc:mysql://localhost:3306/organisationworkspace
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    database: mysql
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notifications
